const stocks = [
  // ================= INDIA (NSE) STOCKS =================
  {
    symbol: "RELIANCE.NS",
    companyName: "Reliance Industries",
    sector: "Energy",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "TCS.NS",
    companyName: "Tata Consultancy Services",
    sector: "IT",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "INFY.NS",
    companyName: "Infosys",
    sector: "IT",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "HDFCBANK.NS",
    companyName: "HDFC Bank",
    sector: "Banking",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "ICICIBANK.NS",
    companyName: "ICICI Bank",
    sector: "Banking",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "SBIN.NS",
    companyName: "State Bank of India",
    sector: "Banking",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "TATAMOTORS.NS",
    companyName: "Tata Motors",
    sector: "Automobile",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "LT.NS",
    companyName: "Larsen & Toubro",
    sector: "Engineering",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "BHARTIARTL.NS",
    companyName: "Bharti Airtel",
    sector: "Telecom",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "MARUTI.NS",
    companyName: "Maruti Suzuki",
    sector: "Automobile",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "TITAN.NS",
    companyName: "Titan Company",
    sector: "Consumer Goods",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "HINDUNILVR.NS",
    companyName: "Hindustan Unilever",
    sector: "FMCG",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "ITC.NS",
    companyName: "ITC Limited",
    sector: "FMCG",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "ZOMATO.NS",
    companyName: "Zomato Limited",
    sector: "Consumer Tech",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "ASIANPAINT.NS",
    companyName: "Asian Paints",
    sector: "Paints & Home Décor",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "AXISBANK.NS",
    companyName: "Axis Bank",
    sector: "Banking",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "KOTAKBANK.NS",
    companyName: "Kotak Mahindra Bank",
    sector: "Banking",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "WIPRO.NS",
    companyName: "Wipro Limited",
    sector: "IT",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "BAJFINANCE.NS",
    companyName: "Bajaj Finance",
    sector: "Financial Services",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "SUNPHARMA.NS",
    companyName: "Sun Pharmaceutical",
    sector: "Healthcare",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "TATASTEEL.NS",
    companyName: "Tata Steel",
    sector: "Metals",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "NTPC.NS",
    companyName: "NTPC Limited",
    sector: "Energy & Utilities",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "POWERGRID.NS",
    companyName: "Power Grid Corp",
    sector: "Utilities",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "M&M.NS",
    companyName: "Mahindra & Mahindra",
    sector: "Automobile",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "ULTRACEMCO.NS",
    companyName: "UltraTech Cement",
    sector: "Materials",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "HCLTECH.NS",
    companyName: "HCL Technologies",
    sector: "IT",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "ADANIENT.NS",
    companyName: "Adani Enterprises",
    sector: "Conglomerate",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "DRREDDY.NS",
    companyName: "Dr. Reddy's Laboratories",
    sector: "Healthcare",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "NESTLEIND.NS",
    companyName: "Nestle India",
    sector: "FMCG",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "JSWSTEEL.NS",
    companyName: "JSW Steel",
    sector: "Metals",
    exchange: "NSE",
    country: "IN",
    currency: "INR",
  },

  // ================= INDIA (BSE) STOCKS =================
  {
    symbol: "RELIANCE.BO",
    companyName: "Reliance Industries (BSE)",
    sector: "Energy",
    exchange: "BSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "TCS.BO",
    companyName: "Tata Consultancy Services (BSE)",
    sector: "IT",
    exchange: "BSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "INFY.BO",
    companyName: "Infosys (BSE)",
    sector: "IT",
    exchange: "BSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "HDFCBANK.BO",
    companyName: "HDFC Bank (BSE)",
    sector: "Banking",
    exchange: "BSE",
    country: "IN",
    currency: "INR",
  },
  {
    symbol: "TATAMOTORS.BO",
    companyName: "Tata Motors (BSE)",
    sector: "Automobile",
    exchange: "BSE",
    country: "IN",
    currency: "INR",
  },

  // ================= US (NYSE / NASDAQ) STOCKS =================
  {
    symbol: "AAPL",
    companyName: "Apple Inc.",
    sector: "Technology",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "MSFT",
    companyName: "Microsoft Corporation",
    sector: "Software & Cloud",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "NVDA",
    companyName: "NVIDIA Corporation",
    sector: "Semiconductors & AI",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "GOOGL",
    companyName: "Alphabet Inc.",
    sector: "Technology & Internet",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "AMZN",
    companyName: "Amazon.com Inc.",
    sector: "E-Commerce & Cloud",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "META",
    companyName: "Meta Platforms",
    sector: "Social Media & Tech",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "TSLA",
    companyName: "Tesla Inc.",
    sector: "Automotive & Clean Energy",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "NFLX",
    companyName: "Netflix Inc.",
    sector: "Entertainment & Streaming",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "AMD",
    companyName: "Advanced Micro Devices",
    sector: "Semiconductors",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "BRK-B",
    companyName: "Berkshire Hathaway",
    sector: "Financial Conglomerate",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "JPM",
    companyName: "JPMorgan Chase & Co.",
    sector: "Banking & Financials",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "V",
    companyName: "Visa Inc.",
    sector: "Financial Technology",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "WMT",
    companyName: "Walmart Inc.",
    sector: "Consumer Retail",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "COST",
    companyName: "Costco Wholesale",
    sector: "Consumer Retail",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "DIS",
    companyName: "The Walt Disney Company",
    sector: "Entertainment & Media",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "CRM",
    companyName: "Salesforce Inc.",
    sector: "Enterprise Software",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "ORCL",
    companyName: "Oracle Corporation",
    sector: "Cloud Infrastructure",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "MA",
    companyName: "Mastercard Incorporated",
    sector: "Financial Technology",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "PG",
    companyName: "Procter & Gamble",
    sector: "Consumer Goods",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "JNJ",
    companyName: "Johnson & Johnson",
    sector: "Healthcare",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "AVGO",
    companyName: "Broadcom Inc.",
    sector: "Semiconductors",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "LLY",
    companyName: "Eli Lilly and Company",
    sector: "Healthcare & Pharma",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "UNH",
    companyName: "UnitedHealth Group",
    sector: "Healthcare",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "HD",
    companyName: "The Home Depot",
    sector: "Consumer Retail",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "ADBE",
    companyName: "Adobe Inc.",
    sector: "Software & Creative",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "INTC",
    companyName: "Intel Corporation",
    sector: "Semiconductors",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "CSCO",
    companyName: "Cisco Systems",
    sector: "Networking & Infrastructure",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "PEP",
    companyName: "PepsiCo Inc.",
    sector: "Consumer Goods",
    exchange: "NASDAQ",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "KO",
    companyName: "The Coca-Cola Company",
    sector: "Consumer Goods",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
  {
    symbol: "BAC",
    companyName: "Bank of America",
    sector: "Banking & Financials",
    exchange: "NYSE",
    country: "US",
    currency: "USD",
  },
];

module.exports = stocks;